In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
%matplotlib inline

In [8]:
filename = "data/2004_indicators.csv"
n = sum(1 for line in open(filename)) - 1 #number of records in file (excludes header)
s = 10000 #desired sample size
skip = sorted(random.sample(xrange(1,n+1),n-s)) #the 0-indexed header will not be included in the skip list
df = pd.read_csv(filename, skiprows=skip)

In [34]:
hubs = df.groupby(['Origin','UniqueCarrier']).count()

In [23]:
lat_lon = pd.read_csv('data/LatLon.csv', names=['AIRPORT_CODE','POINT_LAT','POINT_LON','MODE_AIR'])

In [24]:
lat_lon.columns

Index([u'AIRPORT_CODE', u'POINT_LAT', u'POINT_LON', u'MODE_AIR'], dtype='object')

In [25]:
test = lat_lon[lat_lon['AIRPORT_CODE'].notnull()]
#aircodes = test[test['MODE_AIR']==1]
aircodes2 = test[test['MODE_AIR']==1]

In [26]:
print len(df['Origin'].unique()), len(aircodes['AIRPORT_CODE'].unique())

258 666

In [9]:
airport_lon_lat2 = {}
for row in aircodes.values:
    airport_lon_lat2[row[0]] = \
    (row[1],row[2])

In [30]:
origin_gps = []
dest_gps = []
for code in df['Origin']:
    if code not in airport_lon_lat.keys():
        origin_gps.append((0,0))
    else:
        origin_gps.append(airport_lon_lat[code])
for code in df['Dest']:
    if code not in airport_lon_lat.keys():
        dest_gps.append((0,0))
    else:
        dest_gps.append(airport_lon_lat[code])
print len(origin_gps), len(dest_gps)

10000 10000

In [14]:
series = pd.Series(origin_gps)

In [18]:
print series[series==(0,0)]

565     (0, 0)
642     (0, 0)
689     (0, 0)
840     (0, 0)
1383    (0, 0)
1950    (0, 0)
1951    (0, 0)
2226    (0, 0)
2299    (0, 0)
2337    (0, 0)
2346    (0, 0)
2436    (0, 0)
2804    (0, 0)
3059    (0, 0)
3145    (0, 0)
3152    (0, 0)
3169    (0, 0)
3208    (0, 0)
3217    (0, 0)
3946    (0, 0)
3958    (0, 0)
4010    (0, 0)
4012    (0, 0)
4076    (0, 0)
4207    (0, 0)
4485    (0, 0)
4538    (0, 0)
4717    (0, 0)
4839    (0, 0)
5475    (0, 0)
5549    (0, 0)
6447    (0, 0)
6459    (0, 0)
6472    (0, 0)
6494    (0, 0)
7244    (0, 0)
7267    (0, 0)
7453    (0, 0)
7872    (0, 0)
7878    (0, 0)
8040    (0, 0)
8158    (0, 0)
8168    (0, 0)
8179    (0, 0)
8415    (0, 0)
8963    (0, 0)
9020    (0, 0)
9650    (0, 0)
9831    (0, 0)
dtype: object

In [31]:
df['Origin_GPS'] = pd.Series(origin_gps)

,Unnamed: 0,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,ActualElapsedTime,CRSElapsedTime,AirTime,...,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,route,date,Closure,Origin_GPS
0,295,1641.0,1625,2033.0,2003,UA,470,172.0,158,123.0,...,0,0,0,14,0,16,UA ORD MCO,2004-01-02,0,"(-87.898557, 41.98227)"
1,639,1020.0,1020,1216.0,1225,UA,478,116.0,125,102.0,...,0,0,0,0,0,0,UA MCO IAD,2004-01-20,0,"(-81.316015, 28.428895)"
2,1863,1259.0,1300,1514.0,1512,UA,509,135.0,132,111.0,...,0,0,0,0,0,0,UA IAD MCO,2004-01-18,0,"(-77.45581, 38.94453)"
3,2049,1922.0,1820,2216.0,2113,UA,514,114.0,113,73.0,...,0,0,0,1,0,62,UA ORD CLT,2004-01-23,0,"(-87.898557, 41.98227)"
4,3052,1811.0,1800,2118.0,2120,UA,540,127.0,140,100.0,...,0,0,0,0,0,0,UA ORD BOS,2004-01-14,0,"(-87.898557, 41.98227)"
5,4584,1006.0,1015,1244.0,1247,UA,576,98.0,92,77.0,...,0,0,0,0,0,0,UA DEN MCI,2004-01-31,0,"(-104.667, 39.85841)"
6,4877,1642.0,1643,1915.0,1920,UA,583,273.0,277,252.0,...,0,0,0,0,0,0,UA BOS DEN,2004-01-26,0,"(-71.017496, 42.36852)"
7,5233,1125.0,1130,1401.0,1347,UA,593,216.0,197,192.0,...,0,0,0,0,0,0,UA MIA ORD,2004-01-21,0,"(-80.279913, 25.793836)"
8,5253,1456.0,1450,1713.0,1705,UA,593,257.0,255,230.0,...,0,0,0,0,0,0,UA ORD SNA,2004-01-16,0,"(-87.898557, 41.98227)"
9,5992,1257.0,1300,1520.0,1545,UA,614,83.0,105,73.0,...,0,0,0,0,0,0,UA ORD DCA,2004-01-24,0,"(-87.898557, 41.98227)"
10,6343,1648.0,1600,1849.0,1710,UA,623,181.0,130,100.0,...,0,0,0,99,0,0,UA DCA ORD,2004-01-23,0,"(-77.041934, 38.853032)"
11,6353,1832.0,1800,2101.0,2054,UA,624,89.0,114,70.0,...,0,0,0,0,0,0,UA ORD DCA,2004-01-04,0,"(-87.898557, 41.98227)"
12,6367,1758.0,1800,2040.0,2047,UA,624,102.0,107,77.0,...,0,0,0,0,0,0,UA ORD DCA,2004-01-18,0,"(-87.898557, 41.98227)"
13,7481,1309.0,1315,1604.0,1600,UA,662,115.0,105,92.0,...,0,0,0,0,0,0,UA LAS DEN,2004-01-29,0,"(-115.152315, 36.08038)"
14,7755,902.0,900,1226.0,1206,UA,674,144.0,126,86.0,...,0,0,0,20,0,0,UA ORD LGA,2004-01-05,0,"(-87.898557, 41.98227)"
15,11270,1436.0,1355,2109.0,1944,UA,766,273.0,229,199.0,...,0,0,0,85,0,0,UA SMF ORD,2004-01-23,0,"(-121.59078, 38.69542)"
16,12286,957.0,1010,1044.0,1051,UA,793,107.0,101,80.0,...,0,0,0,0,0,0,UA PIT ORD,2004-01-14,0,"(-80.23287, 40.49147)"
17,13531,652.0,700,931.0,947,UA,869,339.0,347,310.0,...,0,0,0,0,0,0,UA IAD SFO,2004-01-18,0,"(-77.45581, 38.94453)"
18,13692,1638.0,1600,1755.0,1719,UA,874,77.0,79,55.0,...,0,0,0,36,0,0,UA MSP ORD,2004-01-21,0,"(-93.21423, 44.879112)"
19,14813,814.0,820,1545.0,1603,UA,916,271.0,283,253.0,...,0,0,0,0,0,0,UA SEA IAD,2004-01-24,0,"(-122.305006, 47.44772)"
20,15985,853.0,900,1702.0,1720,UA,956,309.0,320,291.0,...,0,0,0,0,0,0,UA SFO JFK,2004-01-22,0,"(-122.385834, 37.616801)"
21,16313,1426.0,1427,1616.0,1623,UA,969,230.0,236,216.0,...,0,0,0,0,0,0,UA BWI DEN,2004-01-30,0,"(-76.683406, 39.185072)"
22,16563,633.0,640,747.0,756,UA,979,74.0,76,58.0,...,0,0,0,0,0,0,UA SFO LAX,2004-01-18,0,"(-122.385834, 37.616801)"
23,16791,1454.0,1455,1612.0,1611,UA,988,78.0,76,60.0,...,0,0,0,0,0,0,UA LAX SFO,2004-01-31,0,"(-118.40807, 33.94254)"
24,16925,1658.0,1700,1813.0,1818,UA,993,75.0,78,54.0,...,0,0,0,0,0,0,UA SFO LAX,2004-01-17,0,"(-122.385834, 37.616801)"
25,16929,1659.0,1700,1815.0,1818,UA,993,76.0,78,55.0,...,0,0,0,0,0,0,UA SFO LAX,2004-01-21,0,"(-122.385834, 37.616801)"
26,17345,1007.0,1010,1209.0,1224,UA,1014,122.0,134,102.0,...,0,0,0,0,0,0,UA DFW ORD,2004-01-06,0,"(-97.03756, 32.8964)"
27,18232,1028.0,1019,1153.0,1204,UA,1054,145.0,165,120.0,...,0,0,0,0,0,0,UA DEN SFO,2004-01-22,0,"(-104.667, 39.85841)"
28,18357,1538.0,1540,1721.0,1727,UA,1058,103.0,107,88.0,...,0,0,0,0,0,0,UA TUS DEN,2004-01-11,0,"(-110.94103, 32.11608)"
29,19081,721.0,725,905.0,915,UA,1078,104.0,110,91.0,...,0,0,0,0,0,0,UA TUS DEN,2004-01-01,0,"(-110.94103, 32.11608)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,7104529,1045.0,1045,1156.0,1205,DL,595,71.0,80,53.0,...,0,0,0,0,0,0,DL SDF ATL,2004-12-03,0,"(-85.736, 38.17439)"
9971,7104822,2008.0,2011,2133.0,2145,DL,850,85.0,94,64.0,...,0,0,0,0,0,0,DL ATL CMH,2004-12-03,0,"(-84.439813, 33.640446)"
9972,7105585,1844.0,1845,2146.0,2146,DL,1662,122.0,121,99.0,...,0,0,0,0,0,0,DL MSY CVG,2004-12-03,0,"(-90.25803, 29.99339)"
9973,7106022,1414.0,1400,1615.0,1602,DL,194,121.0,122,98.0,...,0,0,0,0,0,0,DL ATL JFK,2004-12-04,0,"(-84.439813, 33.640446)"
9974,7109992,NaN,1045,NaN,1205,DL,595,NaN,80,NaN,...,0,0,0,0,0,0,DL SDF ATL,2004-12-06,0,"(-85.736, 38.17439)"
9975,7109999,1603.0,1605,1735.0,1748,DL,600,92.0,103,71.0,...,0,0,0,0,0,0,DL PHX SLC,2004-12-06,0,"(-112.01103, 33.435335)"
9976,7112150,951.0,957,1348.0,1329,DL,819,177.0,152,131.0,...,0,0,0,19,0,0,DL MSP ATL,2004-12-07,0,"(-93.21423, 44.879112)"
9977,7112462,1547.0,1540,1803.0,1750,DL,1106,136.0,130,113.0,...,0,0,0,0,0,0,DL MCO CVG,2004-12-07,0,"(-81.316015, 28.428895)"
9978,7114021,1102.0,1110,1812.0,1820,DL,810,250.0,250,222.0,...,0,0,0,0,0,0,DL LAX CVG,2004-12-08,0,"(-118.40807, 33.94254)"
9979,7114485,1842.0,1850,1956.0,1950,DL,1227,134.0,120,97.0,...,0,0,0,0,0,0,DL SLC SJC,2004-12-08,0,"(-111.981, 40.7859)"
9980,7118136,1627.0,1551,1746.0,1725,DL,1126,79.0,94,59.0,...,0,0,0,21,0,0,DL TPA ATL,2004-12-10,0,"(-82.53325, 27.97547)"
9981,7118668,1312.0,1313,1348.0,1354,DL,1725,96.0,101,77.0,...,0,0,0,0,0,0,DL ATL MSY,2004-12-10,0,"(-84.439813, 33.640446)"
9982,7118825,629.0,630,727.0,734,DL,1908,58.0,64,37.0,...,0,0,0,0,0,0,DL LGA BOS,2004-12-10,0,"(-73.87261, 40.77724)"
9983,7120571,1430.0,1430,1523.0,1534,DL,1924,53.0,64,31.0,...,0,0,0,0,0,0,DL LGA BOS,2004-12-11,0,"(-73.87261, 40.77724)"
9984,7122122,545.0,550,728.0,715,DL,1605,103.0,85,84.0,...,0,0,0,0,0,0,DL TPA ATL,2004-12-12,0,"(-82.53325, 27.97547)"
9985,7122276,744.0,745,1509.0,1452,DL,1778,265.0,247,221.0,...,0,0,0,17,0,0,DL SNA ATL,2004-12-12,0,"(-117.86822, 33.67567)"
9986,7123475,1901.0,1905,2111.0,2115,DL,1021,250.0,250,220.0,...,0,0,0,0,0,0,DL ATL TUS,2004-12-13,0,"(-84.439813, 33.640446)"
9987,7124594,1533.0,1535,1736.0,1745,DL,302,123.0,130,96.0,...,0,0,0,0,0,0,DL ATL EWR,2004-12-14,0,"(-84.439813, 33.640446)"
9988,7124609,1236.0,1237,1452.0,1448,DL,320,136.0,131,114.0,...,0,0,0,0,0,0,DL ATL EWR,2004-12-14,0,"(-84.439813, 33.640446)"
9989,7124902,2009.0,2009,2206.0,2158,DL,596,117.0,109,90.0,...,0,0,0,0,0,0,DL ATL CLE,2004-12-14,0,"(-84.439813, 33.640446)"
9990,7125115,615.0,620,755.0,814,DL,781,100.0,114,83.0,...,0,0,0,0,0,0,DL PHL CVG,2004-12-14,0,"(-75.242636, 39.876302)"
9991,7126339,1119.0,1125,1411.0,1416,DL,2080,172.0,171,140.0,...,0,0,0,0,0,0,DL FLL BDL,2004-12-14,0,"(-80.15275, 26.07258)"
9992,7126806,1943.0,1950,2132.0,2143,DL,611,109.0,113,86.0,...,0,0,0,0,0,0,DL CLE ATL,2004-12-15,0,"(-81.841445, 41.411595)"
9993,7127691,703.0,655,1419.0,1409,DL,1522,256.0,254,227.0,...,0,0,0,0,0,0,DL PDX CVG,2004-12-15,0,"(-122.5948, 45.58771)"
9994,7127942,1441.0,1445,1505.0,1506,DL,1771,84.0,81,63.0,...,0,0,0,0,0,0,DL SLC LAS,2004-12-15,0,"(-111.981, 40.7859)"
9995,7128105,1132.0,1130,1244.0,1230,DL,1950,72.0,60,47.0,...,0,0,0,0,0,0,DL DCA LGA,2004-12-15,0,"(-77.041934, 38.853032)"
9996,7128723,840.0,835,1038.0,1031,DL,641,118.0,116,80.0,...,0,0,0,0,0,0,DL ATL MIA,2004-12-16,0,"(-84.439813, 33.640446)"
9997,7128874,909.0,915,1144.0,1203,DL,781,155.0,168,133.0,...,0,0,0,0,0,0,DL CVG MIA,2004-12-16,0,"(-84.66217, 39.04614)"
9998,7129059,1652.0,1652,1722.0,1726,DL,953,90.0,94,75.0,...,0,0,0,0,0,0,DL ATL BTR,2004-12-16,0,"(-84.439813, 33.640446)"
9999,7129178,721.0,720,859.0,838,DL,1059,158.0,138,119.0,...,0,0,0,21,0,0,DL ATL DFW,2004-12-16,0,"(-84.439813, 33.640446)"